{% set name = "example-robot-data" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Gepetto/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 943e59fe5ab071f83729197584b452e8890562b36b391b0b4042867de034c2b5

build:
  noarch: python
  number: 3

requirements:
  build:
    - python >=3.8
    - numpy
    - cmake
    - make  # [not win]
  host:
    - python >=3.8
    - eigenpy
    - pinocchio >=2,<4
    - numpy
  run:
    - python >=3.8
    - numpy
    - pinocchio >=2,<4

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
  imports:
    - example_robot_data

about:
  home: http://github.com/Gepetto/example-robot-data
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Set of robot URDFs for benchmarking and developed examples
  dev_url: https://github.com/Gepetto/example-robot-data

extra:
  recipe-maintainers:
    - jorisv
    - jcarpent
