{% set name = "example-robot-data" %}
{% set version = "4.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Gepetto/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 173776db171058853f083aad6d43e3f3c6c960d030665b02866d0d0597dd74e3

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_win-64  # [win64]
    - vs2017_win-32  # [win32]
    - cmake
    - make  # [not win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pinocchio                              # [build_platform != target_platform]
  host:
    - python
    - pinocchio
    - numpy
  run:
    - python
    - {{ pin_compatible('pinocchio', min_pin='x.x') }}
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
  imports:
    - example_robot_data

about:
  home: http://github.com/Gepetto/example-robot-data
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Set of robot URDFs for benchmarking and developed examples
  dev_url: https://github.com/Gepetto/example-robot-data

extra:
  recipe-maintainers:
    - jcarpent
